schema_version = "1.0.0"

id = "see_sharp_renderer"
version = "1.0.0"
name = "SeeSharp renderer"
tagline = "Extension to export scenes for SeeSharp"
maintainer = "Pascal Grittmann"
type = "add-on"

website = "https://github.com/pgrit/SeeSharp"

tags = ["Render", "Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:MIT",
]
copyright = [
  "2020-2025 Pascal Grittmann",
]

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "../dist/seesharp_binaries-1.0.0-py3-none-any.whl",
]

[permissions]
files = "Export SeeSharp scene data to disk"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
